### ISSUE TITLE
iOS: Conflict when using react-native-svg with other dependencies that require ReactNativeART

### ISSUE THREAD

**Issue by ryd0rz** [magicismight/react-native-svg#107]
I am trying to use react-native-svg in parallel with react-native-circular-progress for one of my projects.

react-native-circular-progress depends on ReactNativeART, so I added the library and linked the libART.a binary in the build phase of my project.

It appears that react-native-svg is over-riding: RCTConvert. I am getting the following error message (red box): 
"console.error: "Invalid CGPath type 4 at element 4 of (0, "26.25", 15, 4, 15, 15, "11.25", 0, "6.283185307179586", 1 )".

Could it be that react-native-circular-progress (or other libraries using reactNativeART) is referencing the react-native-svg utilities... and if so, is this by design?

**Comment by magicismight** [comment]
react-native-svg first version was based on reactNativeART.
So, there are some files have the same name the reactNativeART.
I`ll fix this later

**Comment by sinansonmez** [comment]
As far as I read this issue is fixed but I am still getting same error. 

> "Invalid CGPath type 4 at element 4 of (0, "59.33544", "3.5", 2, <null>, <null>)".

My package.json file
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^32.0.0",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-paper": "^2.13.0",
    "react-native-progress": "^3.6.0",
    "react-native-svg-charts": "^5.2.0",
    "react-navigation": "^3.6.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "eslint": "^5.14.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "jest-expo": "^32.0.0"
  },
  "private": true
}
```

**Comment by chohonest** [comment]
I am having the same issue.
