### ISSUE TITLE
Question:Will it  be an good solutions for icons SVG Sprites ?

### ISSUE THREAD

**Issue by JackPu** [magicismight/react-native-svg#16]
I have tried **[svg sprites](https://css-tricks.com/svg-sprites-use-better-icon-fonts/)** on my web.I am so excited to find **react-native-art-svg.**We can move it to my react-native app 😊

**Comment by magicismight** [comment]
No.
I don`t think svg sprites will be a good idea in React Native.
It will cause much more unnecessary paint in the native code.

BTW:
This package name has changed into `react-native-svg`.
And it is no longer based on ReactNativeART any more.
You can install react-native-svg and link the native code inside.
`react-native-svg` supports more features while ART don`t have.

**Comment by dubert** [comment]
I would recommend using a custom font and mapping keys to custom characters.
