### ISSUE TITLE
Inconsistent usage of react-native-svg and react-native-art-svg

### ISSUE THREAD

**Issue by mrozbarry** [magicismight/react-native-svg#18]
Documentation and examples aren't consistent.  Some files refer to this package as 'react-native-art-svg' while others as 'react-native-svg'.

**Comment by magicismight** [comment]
Sorry about that.
I have just moved `react-native-art-svg` to `react-native-svg`.
I`ll fix this later.

**Comment by MoOx** [comment]
You should also rename the repo, github now handle redirections.

**Comment by magicismight** [comment]
@MoOx Good idea :+1: 
Just did that.
