### ISSUE TITLE
'Gradient' can only receive 'Stop' elements as children

### ISSUE THREAD

**Issue by abejfehr** [magicismight/react-native-svg#31]
Coming from [this issue](https://github.com/magicismight/react-native-svg/issues/13#issuecomment-207178409), I find that the same "SVG" I pasted in that issue gives me an error in `react-native-svg`. For some reason, my Stop elements must not have the 'Stop' type. Is this a bug?

In the meantime I'm also going to try upgrading my `react-native` version to see if that solves the issue

**Comment by abejfehr** [comment]
I'm afraid that the issue still persists. I took the import statement from the readme.io file and the code is the same as the previous issue, so I won't re-post that here.

**Comment by magicismight** [comment]
Sorry
I didn\`t notice that you have used the wrong prop `stop-color`.
We use camel case as a prop name like: `stopColor`.
And there is something wrong with warning in Gradient elements, I`ll fix that later.

**Comment by magicismight** [comment]
If the issue still persists.
Feel free to reopen this.
