### ISSUE TITLE
React-native 0.25 is available, could the code be updated to use this version

### ISSUE THREAD

**Issue by pietgk** [magicismight/react-native-svg#35]
Hello,

how is the migration to newer released (like 0.25) planned?

**Comment by magicismight** [comment]
Done.

**Comment by pietgk** [comment]
I am using it and the warnings on react / react-native or gone for me.
as far as i can tell its working for me.
thx for the update.

**Comment by magicismight** [comment]
I think this have been fixed in 2.0.0
Everthing works fine on 0.25.1 and 0.26.0.
So I`m closing this.
