### ISSUE TITLE
strokeDasharray not used on Android

### ISSUE THREAD

**Issue by bburnham** [magicismight/react-native-svg#36]
Using the strokeDasharray on android is not creating an appropriate line dash like it does on iOS.

      <Path
        d='M0 0 L0 100'
        fill='none'
        stroke={this.props.primaryColor}
        strokeDasharray='3,3'
        strokeLinecap='butt'
        opacity='0.5'
      />

**Comment by magicismight** [comment]
Everything works fine on react-native-svg@1.2.6 + react-native@0.24.0

```
<Svg height="80" width="225">
            <Path
                d='M0 0 L0 100'
                fill='none'
                stroke='red'
                strokeDasharray='3,3'
                strokeLinecap='butt'
                opacity='0.5'
            />
 </Svg>;
```

**Comment by magicismight** [comment]
I`m closing this.
Feel free to reopen this.
