### ISSUE TITLE
Import broken in master

### ISSUE THREAD

**Issue by gorangajic** [magicismight/react-native-svg#40]
in https://github.com/magicismight/react-native-svg/commit/4af7dc664b5db8feb5bc4bab2b65639f829d1905 you have changed how you include createReactNativeComponentClass and now that is broken
```
import createReactNativeComponentClass from 'react/lib/createReactNativeComponentClass';
```

**Comment by magicismight** [comment]
Fixed in #41 .
Thanks for reporting this.
I`m closing this issue now
