### ISSUE TITLE
Package doesn't work for babel-core 6.8.0+

### ISSUE THREAD

**Issue by saeho** [magicismight/react-native-svg#43]
The entire package does not work with babel-core 6.8.0+.

The reason is because the "this" context does not get passed into almost all of the written code.

i.e.

getChldren() = () => { ... }

this context is not available inside the above code because this is incorrect. It should be...

getChildren() { ... }

The same issue is prevalent pretty much in all of the package.

**Comment by saeho** [comment]
Correction. In the example above, inside the () => {}, this context of the CLASS that this function is in, is not available. They must all change (){...} in order for this package to work for babel-core 6.8.0+

**Comment by tuneZola** [comment]
Thanks, @saeho, that would explain why I am not getting anything to render. Do you know the highest version of babel it works with?

**Comment by saeho** [comment]
6.6.4 works. I'm not sure about 6.7. Haven't tried anything beyond 6.6.4

**Comment by magicismight** [comment]
I\`m closing this now.
Because the related code are no longer existed on the latest version
