### ISSUE TITLE
[Q] Why it NO LONGER rely on ReactNativeART?

### ISSUE THREAD

**Issue by nvcken** [magicismight/react-native-svg#49]
Just want to know reason

**Comment by magicismight** [comment]
ART is only a part of svg，cannot implent all svg features by ART. ART only accepts the common features which are shares by SVG，VML and canvas.
For example，the fillRule feature which I had sent a PR to ReactNativeART few weeks ago is denied for it is just a SVG feature,not shared by VML and canvas.

**Comment by caledhwa** [comment]
I'm working on a chart app based on this library. For the most part, it's working great for me. I fully support that you've migrated away from ART. My library should be available in a month or so

Get Outlook for iOS




On Wed, May 25, 2016 at 5:12 PM -0700, "Horcrux" <notifications@github.com> wrote:












ART is only a part of svg，cannot implent all svg features by ART. ART only accepts the common features which are shares by SVG，VML and canvas.

For example，the fillRule feature which I had sent a PR to ReactNativeART few weeks ago is denied for it is just a SVG feature,not shared by VML and canvas.
