### ISSUE TITLE
Is there an way to convert the Svg to png stuff

### ISSUE THREAD

**Issue by nihgwu** [magicismight/react-native-svg#52]
I've test this component in my app to replace all the font icons to svg ones, and it's so great that it works perfectly both on iOS and Android.
but on Android, it force closed if i use the svg icon in `ListView`, i'think perhaps it's not a good way because the icon will be render in every `renderRow` method, and it will cause perf issue(?)
so i'm wondering is there an way to render the icon just once( export to a `Image` source for example) and then be used in the `ListView` as they are all the same

**Comment by clozr** [comment]
react-native-vector-icons does this automatically for you.
When you use a certain icon inside <Icon name="your-icon-name" /> component it will dynamically generated the image.

**Comment by hezheop** [comment]
+1,I use this to draw line on phone when touch onMove,just like view.props.onResponderMove, but when I append string to Path.d, The string becomes so long  and it take much memory, so i want convert svg to  image ,i maybe solve my problem i think, what should I do ? thanks :)

**Comment by magicismight** [comment]
Try this:
```
svgRef.toDataURL(base64 => {
    console.log(base64);
});
```
This is a new feature finished recently.

**Comment by henrikra** [comment]
I am also having performance issues if I am rendering multiple (8 in this case) icons inside ListView.  Here is gif http://giphy.com/gifs/3o7TKvo0bqXxy60Tdu As you can see sometimes the texts flash in middle of the screen when it hasn't render the icons yet which are svg

**Comment by SuhairZain** [comment]
Hi @magicismight,
When I try to use toDataURL(), I get a `width and height must be > 0` exception. Could you please help me with this?

**Comment by csyfly** [comment]
Hello everyone, I see you are all discussing the issue of converting SVG to PNG. Here's a free online tool: [SVGtoPNG](https://svg-to-png.net/). It doesn't require uploading files, and you can download the converted PNG image immediately.
