### ISSUE TITLE
Scaling SVG with height/width/viewBox?

### ISSUE THREAD

**Issue by hedgerh** [magicismight/react-native-svg#53]
I'm trying to scale my SVG, which has `viewBox='0 0 24 23'`, down to `16 x 16`.  However, when I change the `width/height` properties, the icon does not scale down, it just gets clipped off outside of the `16x16` box.

Icon with `viewBox='0 0 24 23' and `width=24` and `height=23`:
![image](https://cloud.githubusercontent.com/assets/2524280/15819590/1bc30c18-2bb2-11e6-9ce6-f0ba839b19a1.png)

Icon with `viewBox='0 0 24 23' and `width=16` and `height=16`:
![image](https://cloud.githubusercontent.com/assets/2524280/15819608/37ee18a6-2bb2-11e6-95f3-307143e9ba23.png)

Am I missing something here?  Here is my code.

```
import React from 'react'
import Svg, {
  Path
} from 'react-native-svg'

const AlarmIcon = ({width, height, fill, stroke, viewBox, style}) => {
  return (
    <Svg width={width} height={height} viewBox={viewBox} style={style}>
      <Path stroke={stroke} fill={fill} strokeCap='round' strokeJoin='round' d='M20.5,16.5V11A8.5,8.5,0,0,0,15,3,3,3,0,0,0,9,3,8.49,8.49,0,0,0,3.5,11v5.5a3,3,0,0,1-3,3h23A3,3,0,0,1,20.5,16.5Z'/>
      <Path stroke={stroke} fill={fill} strokeCap='round' strokeJoin='round' d='M15,19.5a3,3,0,0,1-6,0'/>
    </Svg>
  )
}

AlarmIcon.defaultProps = {
  width: 24,
  height: 23,
  stroke: '#fff',
  fill: '#fff',
  viewBox: '0 0 24 23'
}

export default AlarmIcon
```

**Comment by hedgerh** [comment]
I managed to get the icon to scale properly by applying `scale={width/24}` to both of the path elements.  Is there a better way to do this, though?

**Comment by rlancer** [comment]
Seems to be a bug with viewBox attribute being ignored on the Svg element.

**Comment by cjbell** [comment]
Just as an update, if you specify a `viewbox` prop instead of `viewBox` it works!

**Comment by magicismight** [comment]
Fixed in 4.0.0-rc
Now you can use `viewbox` or `viewBox` both.
But using `viewbox` will give a deprecated warning.

**Comment by trinadhkoya** [comment]
I am using Tab Navigator(react-navigation) ,i placed the Icon over there,How to change the Active to inactive icon when i tap on other icons?

**Comment by EskelCz** [comment]
Also, the viewbox dimensions should be the original dimensions of the shape.

**Comment by pvsmounish** [comment]
`viewbox` no more works.
Try `viewBox` now.

**Comment by kumarkundan** [comment]
> I managed to get the icon to scale properly by applying `scale={width/24}` to both of the path elements. Is there a better way to do this, though?

Thanks ...I am using scale={.5} on `Path ` tag ...it's working fine

**Comment by Daavidaviid** [comment]
How to scale differently same svg ?
