### ISSUE TITLE
LinearGradient fill on Polygons

### ISSUE THREAD

**Issue by mrozbarry** [magicismight/react-native-svg#54]
When I attempt to fill a polygon with a linear gradient, I just get the following error:

![screen shot 2016-06-06 at 5 40 17 pm](https://cloud.githubusercontent.com/assets/566486/15838750/c723397e-2c0d-11e6-8e43-de5bf6e68766.png)

The examples only use Ellipse, so I don't know if this is only supported on non-polygon elements, or if this is a bug.

My code is as follows:

```jsx
import React, { View } from 'react-native'
import { Svg, Defs, LinearGradient, Stop, G, Polygon } from 'react-native-svg'

export function BlueShard (props) {
  return (
    <View style={props.style}>
      <Svg width="15" height="71">
        <Defs>
          <LinearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="blue-gradient">
            <Stop stopColor="#6ABAD5" stopOpacity="1" offset="0%" />
            <Stop stopColor="#1E9FD6" stopOpacity="1" offset="100%" />
          </LinearGradient>
        </Defs>
        <Polygon fill="url(#blue-gradient)" points='0,0 15,0 0,71' />
      </Svg>
    </View>
  )
}
```

**Comment by magicismight** [comment]
use id="blue"

**Comment by magicismight** [comment]
Use id="blueGradient" you should use camel case in React.
It's a bug when parsing full or stroke like url(#xxx-xxx)
I'll fix this later.

**Comment by mrozbarry** [comment]
That worked, thanks!
