### ISSUE TITLE
Android: SvgView should have explicit width and height set

### ISSUE THREAD

**Issue by mrozbarry** [magicismight/react-native-svg#57]
I have an SvgView that is being super-imposed over a View, but the view has variable width and height.  On iOS, I had no problem specifying `<Svg style={{ position: 'absolute', top: 0, bottom: 0, left: 0, right: 0 }}> ... </Svg>`, but on Android, I get the following error:

![screen shot 2016-06-14 at 3 32 33 pm](https://cloud.githubusercontent.com/assets/566486/16056918/a6a2b948-3245-11e6-903e-fe7bdc562b22.png)

Is this some sort of restriction on android, or a bug?

**Comment by magicismight** [comment]
This had been fixed in [this commit](https://github.com/magicismight/react-native-svg/commit/ce74efc58dc3ddaf625c07bba549c9a7b64ec56a#diff-33c7742dca003adb1756e703ad8ec4c7L33)

**Comment by habeebrahmanpt** [comment]
E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: SurfaceView should have explicit width and height set
        at com.horcrux.svg.SvgViewManager$1.measure(SvgViewManager.java:39)
