### ISSUE TITLE
NativeProps on iOs

### ISSUE THREAD

**Issue by zaynyatyi** [magicismight/react-native-svg#58]
Trying to run it on ios and getting undefined is not an object
![img_0016](https://cloud.githubusercontent.com/assets/327729/16086543/943697dc-3328-11e6-81ce-ef26b98dc280.png)

Tried to use same createNativeComponent as for android but got only red borders there, without content.

**Comment by magicismight** [comment]
Please make sure the library has linked into your project.

**Comment by magicismight** [comment]
It seems like you didn\`t run `rnpm link react-native-svg`

**Comment by zaynyatyi** [comment]
I ran it, but there were no libRNSVG.a and i removed it. Could that be a reason? Where should i get that lib?

**Comment by magicismight** [comment]
That is the reason.
You can add `libRNSVG.a` and try again.

**Comment by zaynyatyi** [comment]
It's weird, i can see lib in Product, but when i'm linking into my project there is no tree in there.
<img width="254" alt="2016-06-16 10 08 35" src="https://cloud.githubusercontent.com/assets/327729/16108181/60bdee96-33aa-11e6-89e3-cdc89227c4ad.png">

**Comment by magicismight** [comment]
Try to reinstall it
```
rm -rf node_modules/
npm i react-native-svg --save
rnpm link react-native-svg
```

**Comment by zaynyatyi** [comment]
That worked, thanks
