### ISSUE TITLE
Does origin/originX/originY affect Scale?

### ISSUE THREAD

**Issue by dubert** [magicismight/react-native-svg#61]
It works perfectly when I use it for rotate, but the origin doesn't seem to be affecting the scale. I'm just doing this:

```js
<G origin={'20, 28'} scale={.5}>
```

Am I missing something?

When I do:
```js
<G origin={'20, 28'} rotate={90}>
```
it works.

**Comment by magicismight** [comment]
I have no idea what`s going on here.
Maybe you can provide more information?
Everything works fine to me.

**Comment by dubert** [comment]
It's pretty complicated and nuanced, so did test of every possible combination of scale and rotate transforms with origins. Then I put them together in this chart, and attempted to show the correct behavior with the transparent versions.
![illustration of svg transforms](https://cloud.githubusercontent.com/assets/1843672/17085196/9f659b6c-51a0-11e6-94d0-ccee4abc27e2.png)

**Comment by magicismight** [comment]
Thanks  for this detailed information.
The 2d matrix libray has several bugs inside,will be replaced with anthor libray instead.
This fix will be landed in next version.
