### ISSUE TITLE
Renders blank on 0.29.0-rc.0

### ISSUE THREAD

**Issue by grabbou** [magicismight/react-native-svg#62]
Might be related to flex layout changes, nothing is rendered, no errors/issues in the console. Tested on iOS. Same code works w/o a single warning on 0.26/0.27 (haven't tested 0.28)

**Comment by magicismight** [comment]
Maybe [this PR in ART](https://github.com/facebook/react-native/commit/b0fed416cbb510009bef1ae721e564d04d053cc5) can fix this.
I`ll try to fix this later.
