### ISSUE TITLE
Style attribute on SVG makes it not render

### ISSUE THREAD

**Issue by mderrick** [magicismight/react-native-svg#63]
Not sure why, but since updating versions an SVG that has a style prop breaks.

e.g an empty object like this means the Circle will no longer show.

```
<Svg style={{}} >
    <Circle />
</Svg>
```

**Comment by lynndylanhurley** [comment]
I'm seeing this, too.

**Comment by magicismight** [comment]
It seems like the Svg element did not have a layout on itself.
If you don`t specify Its width and height or using flex layout. It wont layout itself.

**Comment by magicismight** [comment]
Sorry about this. this is a bug for SVG elements.
Got this been fixed in next version.
