### ISSUE TITLE
Problem `Module not found` in webpack and react-native-svg

### ISSUE THREAD

**Issue by cloady** [magicismight/react-native-svg#68]
ERROR in ./~/react-native-svg/elements/Rect.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../lib/createNativeComponent in /Users/<user>/native-starter-kit/node_modules/react-native-svg/elements
 @ ./~/react-native-svg/elements/Rect.js 40:29-68

Please help to resolve this issue!

Thank you.

**Comment by magicismight** [comment]
Which `react-native-svg` version did you use on your project?
Everything works fine on the latest version

**Comment by magicismight** [comment]
Why did you use webpack?
In fact `lib/createNativeComponent .js` didn`t exist
it appears with `lib/createNativeComponent .ios.js` and `lib/createNativeComponent.android.js`.
It works fine on react-native`s cli packager
