### ISSUE TITLE
Draw pie chart

### ISSUE THREAD

**Issue by vetm73** [magicismight/react-native-svg#69]
I would like to draw a pie chart and found some tutorials to do it in HTML with the attached css. Is it possible to do it this way with react-native-svg?

Kind regards,

Mike

https://css-tricks.com/how-to-make-charts-with-svg/#article-header-id-7

circle {
  fill: #ddd;
  stroke: $primaryColor;
  stroke-width: 50;
  stroke-dasharray: 0 158;
  transition: stroke-dasharray .3s ease;
}

svg {
  margin: 0 auto;
  transform: rotate(-90deg);
  background: #ddd;
  border-radius: 50%;
  display: block;
}

**Comment by magicismight** [comment]
Unfortunately this is not fully supported yet.

**Comment by vetm73** [comment]
Hi,

Thanks for your answer

KIND REGARDS,

MIKE

**Comment by hybrisCole** [comment]
@vetm73 Hey, I made a workaround for this:

```
import React from 'react';
import { Dimensions } from 'react-native';
import Svg, {
    LinearGradient,
    Circle,
    Defs,
    Stop,
    Use,
    Symbol,
    Path,
} from 'react-native-svg';
const {width} = Dimensions.get('window');
const circunference = Math.PI * (70  * 2);
const GoalChart = () => (
  <Svg
    height="100"
    width={width * 0.333}
    viewbox="0 0 280 280"
  >
    <Defs>
      <LinearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
        <Stop offset="0" stopColor="#2E8AEC" stopOpacity="1" />
        <Stop offset="1" stopColor="#3BD8FC" stopOpacity="1" />
      </LinearGradient>
    </Defs>
      <Circle fill="url(#grad)" cx="140" cy="140" r="140"/>
      <Circle rotate="-180" origin="140, 140" fill="url(#grad)" cx="140" cy="140" r="70" stroke="#EAEAEA" strokeDasharray={[circunference * 0.2, circunference]} strokeWidth="140"/>
  </Svg>
);

export default GoalChart;
```

**Comment by hybrisCole** [comment]
Be aware that `circunference * 0.2` means the amount of char that will not be dashed, so in that case that would mean 80% filled

**Comment by vetm73** [comment]
Hi Alberto,

Tnx for your workaround. I’ll go and give it a try.

Kind regards,
Mike

**Comment by kevinbarabash** [comment]
You could use a `<Path>` element to draw each of the segments that make up the pie chart.

**Comment by gijoehosaphat** [comment]
I use this method to generate a Pie chart with a value (percentage).

`
const pie = (radius, value) => {
  const x = radius - Math.cos((2 * Math.PI) / (100 / value)) * radius
  const y = radius + Math.sin((2 * Math.PI) / (100 / value)) * radius
  const long = (value <= 50) ? 0 : 1
  const d = `M${radius},${radius} L${radius},${0}, A${radius},${radius} 0 ${long},1 ${y},${x} Z`

  return d
}
`

Just pass the returned `d` to your `Path`.
`radius` is your size, `value` is the percentage around you want to go. Starts at the top.

**Comment by hybrisCole** [comment]
hello @gijoehosaphat do you have a guide to learn how to work with <Path's ?

**Comment by gijoehosaphat** [comment]
They are very easy, but generating their value isn't always easy:

```
  <Svg width={100} height={100}>
      <Defs>
        <ClipPath id={'clip'}>
          <Path d={pie(50, value)} />
        </ClipPath>
      </Defs>
      <SVG.G>
        <Circle cx={50} cy={50} r={50} fill={'#ff0000'} clipPath={'url(#clip)'} />
      </G>
    </Svg>
```

If you want to learn more about Path's in general and SVG's I would hit up the Tutorials linked in the README of this repo.

**Comment by magicismight** [comment]
This is supported now.
You can try the [example](https://github.com/magicismight/react-native-svg/blob/master/Example/examples/Circle.js#L66)

**Comment by magicismight** [comment]
![image](https://cloud.githubusercontent.com/assets/7693239/17454084/f4d7849a-5bbc-11e6-8ad6-ecc2cf13477e.png)

**Comment by maluramichael** [comment]
How do i wrap the pie chat in a function e.g. `function pie(percentage) { return <Svg>...</Svg> }` i don't want to struggle with the values. I just want to calculate them from a single percentage value.
