### ISSUE TITLE
[rn 0.29.0] android compile error cause by uimanager TouchEvent.obtain params change

### ISSUE THREAD

**Issue by playing** [magicismight/react-native-svg#70]
after upgrade react native to 0.29.0, react-native-svg will failed in compile. because of this commit https://github.com/facebook/react-native/commit/837aafde72fb43836aa7c36cf66db4e9abae0e17

and error is 
```
 TouchEvent.obtain(
                          ^
  need: int,long,TouchEventType,MotionEvent,float,float,TouchEventCoalescingKeyHelper
  find: int,long,TouchEventType,MotionEvent,float,float
```

in RNSVGSvgView.java

**Comment by playing** [comment]
like react native do, import TouchEventCoalescingKeyHelper and add to TouchEvent.obtain will fix method. at least work in my project.
```java
// add TouchEventCoalescingKeyHelper
import com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper;

private final TouchEventCoalescingKeyHelper mTouchEventCoalescingKeyHelper = new TouchEventCoalescingKeyHelper();

```

**Comment by playing** [comment]
send a pr to fix it #71. please check @magicismight

**Comment by somename85** [comment]
same issue with rn 0.30 and react-native-svg 4.2.0

**Comment by magicismight** [comment]
@somename85 
4.2.0 has changed peerDependency as
```
    "peerDependencies": {
        "react-native": ">=0.32.0"
    }
```

using 4.1.5 instead.

**Comment by somename85** [comment]
@magicismight
my bad, i missed it
thanks a lot )
