### ISSUE TITLE
Error (and solution) to bug in RNSVGSvgView.java: "method obtain in class TouchEvent cannot be applied to given types".

### ISSUE THREAD

**Issue by dvoiss** [magicismight/react-native-svg#72]
```
react-native-svg/Example/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/RNSVGSvgView.java:183: 
  error: method obtain in class TouchEvent cannot be applied to given types;
            TouchEvent.obtain(
                      ^
  required: int,long,TouchEventType,MotionEvent,float,float
  found: int,long,TouchEventType,MotionEvent,float,float,TouchEventCoalescingKeyHelper
  reason: actual and formal argument lists differ in length
```

I've fixed it by removing the last parameter `mTouchEventCoalescingKeyHelper` everywhere the obtain method is used in `RNSVGSvgView`. But I do not know if this is a reasonable fix. I did it so that I could compile the example on Android. 

Thoughts?

edit: also these were my full steps to reproduce from checkout:

```
git clone https://github.com/magicismight/react-native-svg
cd react-native-svg/Example
npm install
cd android
gradle wrapper
cd ..
react-native run-android
```

**Comment by dvoiss** [comment]
This new parameter seems to have been added in the past month here:

https://github.com/facebook/react-native/commit/837aafde72fb43836aa7c36cf66db4e9abae0e17#diff-e7ea49415e6e806c1542e8dd7d09b7da

for `v0.30.0-rc.0`

**Comment by magicismight** [comment]
Try react-native-svg@3.0.0-rc
#71 have fixed this issue

**Comment by heroic** [comment]
Getting this same error with react-native-svg@4.6.1 and react-native@0.44.2

**Comment by cogmeta** [comment]
I am also getting error with react-native-svg@4.6.1 and react-native@0.44.2

**Comment by DavidLi-Minxiao** [comment]
Same error with `react-native-svg@4.4.0` and `react-native@0.46.1`

**Comment by enguerranws** [comment]
Same error with `react-native-svg@5.1.3`.
