### ISSUE TITLE
Breaks on 0.29

### ISSUE THREAD

**Issue by yeegr** [magicismight/react-native-svg#73]
Seems none of the subtags, Path, Rect, Circle are working in the latest build of RN029, had to downgrade to RN028

**Comment by thethanghn** [comment]
+1

**Comment by mattvot** [comment]
Which release version are you using?

**Comment by hybrisCole** [comment]
*Nexus 6P*
![image](https://cloud.githubusercontent.com/assets/951133/16704881/8aa54b4a-453a-11e6-931f-2c5fd39b698f.png)

*iOS Emulator*
![image](https://cloud.githubusercontent.com/assets/951133/16704888/ac0732da-453a-11e6-94b2-2943fb610b60.png)

**Comment by chiechelski** [comment]
Using 3.0.0-rc works for ios, but not for android. I keep getting a red box where should be the SVG component. Is this related to the RN029 issue?

![reactnativesvgerror](https://cloud.githubusercontent.com/assets/6915704/16711491/d988cd9e-46b2-11e6-98cc-3925a6c2c282.png)

Cheers

**Comment by ConanXie** [comment]
@chiechelski 
If using RN v0.29.0, you should change the application template, refer to [Android breaking changes](https://github.com/facebook/react-native/releases).

**Comment by kenchengch** [comment]
same issue here.

**Comment by vetm73** [comment]
I've upgraded my current project to 0.29 and react-native-svg@3.0.0-rc and double checked the [Android breaking changes](https://github.com/facebook/react-native/releases) and see a red border instead of my svg. 
Also tried to install a 'fresh' project which also shows only the red border.

**Comment by kulicuu** [comment]
Also just tested on fresh project with v29, and just getting the red outline on Android.

**Comment by magicismight** [comment]
Everything works fine on `react-native@0.29.0` and `react-native-svg@3.0.0`.
You can try the example project in react-native-svg
Did you forget to link the native code into packages list in mainApplication.java?
```
        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new RNSvgPackage()
            );
        }
```

**Comment by kulicuu** [comment]
awesome clue thank you so much.  wl update shortly.

**Comment by vetm73** [comment]
Jep. Solved. 
import com.horcrux.svg.RNSvgPackage; and new RNSvgPackage() were missing after not paying enough attention when I did react-native update

Thanks for your support.

**Comment by magicismight** [comment]
I`m closing this issue now.
Feel free to reopen this.
