### ISSUE TITLE
Support for hitSlop props

### ISSUE THREAD

**Issue by agenthunt** [magicismight/react-native-svg#81]
Is hitSlop supported for Svg Elements ? Would it be possible to expose hitSlop props for all Svg Elements ?

**Comment by magicismight** [comment]
SVG elements are not standard react-native view-based elements, they are just abstract elements to descript the drawing path and fill stroke rules on SVG context.
It is possible to support hitSlop for all svg elements,but I`m not intend to do this.
Because it is not a standard attribute for svg elements on web.
Unless you can provide me some convinced reason to do this.

**Comment by agenthunt** [comment]
Thanks for the response. I am trying to use this library in  interactive charts. The current hitArea of the any svg element is only its bounding size.  So when it is used as a drag handle, it is very difficult to get hold of it and touchability is poor. The workaround I am using is to create a View component outside of svg in the same path. It is cumbersome to keep track of location both inside svg and outside. hitSlop would make this easier.  I dont think argument "hitSlop not being a standard attribute for svg element" is that helpful, since it already supports touchable props which are also not standard attribute. I think it would helpful to be web svg compliant and extendable to react-native.

**Comment by magicismight** [comment]
And there is another issue with hitSlop.
`hitSlop` prop can work with regular shaped elements like Rect, circle.
But how would you implement it to svg shape like Path, Polygon, Polyline?

You can create a rect with tranparent fill to cover the drag handle element, and bind the responders on the rect,like this:
```
<G x={this.state.x} y={this.state.y}> // the g element do the translate stuff.
...whatever the drag handle element is
<Rect
 x="0"
 y="0"
 width="40"
 height="40"
 fill="rgba(0,0,0,0)"
{{...
    onStartShouldSetResponder: this.touchableHandleStartShouldSetResponder,
    onResponderTerminationRequest: this.touchableHandleResponderTerminationRequest,
     onResponderGrant: this.touchableHandleResponderGrant,
     onResponderMove: this.touchableHandleResponderMove,
     onResponderRelease: this.touchableHandleResponderRelease,
     onResponderTerminate: this.touchableHandleResponderTerminate
}}
/>
</G>
```

**Comment by agenthunt** [comment]
Yes. you are right .
Transparent Rect could work. Thanks
