### ISSUE TITLE
Unable to resolve module react/lib/createReactNativeComponentClass

### ISSUE THREAD

**Issue by edolfuchs** [magicismight/react-native-svg#82]
I install the module as explained in: https://github.com/magicismight/react-native-svg. 

But when importing any module (example: import Svg, {Circle} From 'react-native-svg';)  the following error appears:

Unable to resolve module react/lib/createReactNativeComponentClass...
Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/react/lib/createReactNativeComponentClass and its parent directories

![captura de tela 2016-07-21 as 10 12 57](https://cloud.githubusercontent.com/assets/12100777/17023854/cb52552a-4f2b-11e6-999f-8539fbffddbf.png)

Can anyone help?
Thanks

**Comment by magicismight** [comment]
Which react-native-svg version did use for your project?
You can try the latest stable version `3.1.1` for react-native >= 0.29.0 or use 2.2.0 for react-native < 0.29.0

**Comment by edolfuchs** [comment]
I was using react-native-svg 3.1.1 for react-native 0.21. I updated the react-native version for 0.30 and it worked.

Thanks.

**Comment by uc-spr** [comment]
I also faces same problem. I install the react-native-svg but when I was import to use it's component then it throws same above error. If anyone knows then suggest the answer??

**Comment by edolfuchs** [comment]
This  issue I solved by updating the react-native version to 0.30 and react-native-svg to 3.1.1

**Comment by uc-spr** [comment]
Please suggest if anyone knows..
![simulator screen shot 28-jul-2016 7 11 19 pm](https://cloud.githubusercontent.com/assets/16412211/17214588/4c0c69be-54f7-11e6-89a6-9723ba8d6634.png)

**Comment by uc-spr** [comment]
![2016-07-28_1945](https://cloud.githubusercontent.com/assets/16412211/17215872/028d7990-54fc-11e6-88bf-d9a0081d4609.png)
When i install react@~15.2.0 to use , then it generates fatal error. screencast is pasted above. If anyone knows then please suggest..

**Comment by sjafri5** [comment]
If you're having this issue make sure that the version of react-native-svg you installed matches with the version of react-native you have. That solved the issue for me.

**Comment by hssrrw** [comment]
I see exactly the same issue with `react-native 0.46.3` and `react-native-svg 5.3.0` and have no idea how to solve it 🙁

**Comment by lionel95200x** [comment]
same issue too

**Comment by hssrrw** [comment]
For me problem was in peerDependencies in `react-native-svg-uri` which used outdated `react-native-svg` version incompatible with `react-native 0.46.3`. Fixed that by updating peerDependencies

**Comment by SupriyaKalghatgi** [comment]
same issue
