### ISSUE TITLE
Android: "No ViewManager defined for class RNSVGGroup"

### ISSUE THREAD

**Issue by pallzoltan** [magicismight/react-native-svg#83]
Hello,

I have no problems with iOS but Android gives me redbox with this error. I'm not an Android developer and have no idea where to look next. 
Anyone has an idea what the cause of the problem is?

Thanks,
Z.

**Comment by prontiol** [comment]
@pallzoltan What's your React Native version?

**Comment by pallzoltan** [comment]
It was 0.29.2, but I have since updated to 0.30.0 and removed react-native-svg, I needed to progress. I've never fixed this problem.

Z.

**Comment by prontiol** [comment]
What package did you use as a substitute?

**Comment by pallzoltan** [comment]
I'll go for https://github.com/oblador/react-native-vector-icons Or designer seemed to like the package's contents.

**Comment by prontiol** [comment]
Looks like `rnpm link` does not work well with the latest versions of React Native, so I had to add this package manually.
In MainApplication.java I added the following import:
```
import com.horcrux.svg.RNSvgPackage;
```
also I added RNSvgPackage to the getPackages method like this:
```
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.asList(
        ... other packages ...
        new RNSvgPackage()
    );
}
```

**Comment by magicismight** [comment]
I`m closing this issue.
It seems like you haven`t link the native code into your project.
Try @prontiol `s solution.
Feel free to reopen this if the problem still exsists.

**Comment by CusProjects** [comment]
Please re-open this issue,

 "react": "16.0.0-alpha.6",
 "react-native": "0.44.0",
 "react-native-svg": "5.1.8",

i alredy link the library.

**Comment by DavitVosk** [comment]
It works perfectly on IOS but throws an error for Android: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

To note, all manual linking processes are done. 

Has anyone dealt with this error? And if yes, how can I fix it.

**Comment by DavitVosk** [comment]
Solved.

Make sure you have same versions for

    compileSdkVersion 25
    buildToolsVersion '25.0.0'
and

compile "com.android.support:appcompat-v7:25.0.0"
in your android/app/build.gradle
As described here https://stackoverflow.com/a/42144590

**Comment by GezimPB** [comment]
Saved my day: 🎉 
     .
     .
     .
    "react": "16.3.2",
    "react-native": "^0.55.0",
    "react-native-svg": "^6.3.1",
    .
    .
    .

**Comment by Atdheu06** [comment]
@GezimPB  

>  **# WOW EXCELLENT WORKED FOR ME** 

- 💯 👍 🎉 🌮 🥇
