### ISSUE TITLE
Touch events are not mapped to the viewBox

### ISSUE THREAD

**Issue by steveliles** [magicismight/react-native-svg#96]
In 4.0.0-rc1, if I have an SVG with no viewBox attribute the touch events work correctly - touching the visible shape generates an event, touching outside the shape does not.

If I add a viewBox attribute the touch events aren't translated/scaled into the new viewBox, so touching the visible elements doesn't generate an event, but touching the place where they would appear without the viewBox attribute does generate an event.

**Comment by steveliles** [comment]
I looked at the code a couple days ago for hitTest and figured the problem was that it didn't apply the viewbox matrix ... I was going to have a go at fixing at least for Android which I'm more familiar with, but it seems this was added in yesterday's commit to add touch events to G elements, so I tried with git master - the problem still exists, but it is slightly different.

Previously the touch events were being handled by the element that would have been under your finger if the viewBox were not applied. 

With master _nothing_ seems to receive the event if there is a viewBox - neither the shape that you touch nor the shape that would have been under your finger without the viewBox being applied.

The problem persists even if the viewBox is set to show the exact same portion of the image as with no viewBox (e.g. an SVG with width={100} height={100} and viewBox='0 0 100 100').

**Comment by steveliles** [comment]
I spent a few hours debugging this one and I think its actually down to a problem with nested groups - namely that an enclosing G with no `onPress` steals the event (becomes the event target), though it should not.

This can be seen clearly with a simple example that doesn't involve a ViewBox - the following code correctly echoes "i'm touched" to the console when you tap the circle:
```
<Svg width="100" height="100">
  <G>
    <Circle cx={50} cy={50} r={50} fill='#f00' 
      onPress={()=>{console.log("i'm touched")}}/>
  </G>
</Svg>
```

The following echoes nothing (but should!):
```
<Svg width="100" height="100">
  <G>
    <G>
      <Circle cx={50} cy={50} r={50} fill='#f00' 
        onPress={()=>{console.log("i'm touched")}}/>
    </G>
  </G>
</Svg>
```

And similarly, adding a viewBox attribute to the SVG (without the double nested G tag) echoes nothing - because the viewBox attribute is actually transformed into the equivalent of a nested G tag, making it equivalent to the previous example:
```
<Svg width="100" height="100" viewBox="0 0 100 100">
  <G>
    <Circle cx={50} cy={50} r={50} fill='#f00' 
        onPress={()=>{console.log("i'm touched")}}/>
  </G>
</Svg>
```

I was hoping to attempt a fix, but I don't yet understand how everything hangs together.

I think the problem lies in `RNSVGGroupShadowNode` at line 96:

```
94            viewTag = node.hitTest(point, ((ViewGroup) view).getChildAt(i), combinedMatrix);
95            if (viewTag != -1) {
96                return node.isResponsible() ? viewTag : view.getId();
97            }
```

When viewTag is != -1 because of a direct child's hitTest, line 96 correctly returns the id of the child. 

However, if the viewTag belongs to a more deeply nested descendent then the direct child node (a nested G for example) will return false from `isResponsible` if it doesn't have e.g. an `onPress` callback, and the current element will claim the hit.

**Comment by steveliles** [comment]
Actually pull-request #102 causes the events to be received on iOS, which is an improvement, but still doesn't map them correctly to the viewBox :-S

**Comment by EskelCz** [comment]
I think I'm running into this issue on android, svg element swallowing touch events even when nothing inside it was pressed
